apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configmap-updater
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configmap-updater
        tier: system
    spec:
      containers:
      - name: refresher
        image: docker.astuart.co:5000/k8s/configmap-updater
        imagePullPolicy: Always
        resources:
          requests: &r
            cpu: 100m
            memory: 200Mi
          limits: *r
