apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-configmap-updater
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-configmap-updater
        tier: system
    spec:
      containers:
      - name: refresher
        command:
        - /kube-configmap-updater
        image: andrewstuart/kube-configmap-updater
        imagePullPolicy: Always
        resources:
          requests: &r
            cpu: 100m
            memory: 200Mi
          limits: *r
